### ISSUE TITLE
fastddsspy with idl type

### ISSUE THREAD

**Issue by wannastar** [eProsima/Fast-DDS-spy#52]
![image](https://github.com/eProsima/Fast-DDS-spy/assets/42711319/8e9b684c-d2c7-4e83-a7f0-1d38d637b564)

IDL include a structure HelloWorld, HelloWorld includes a struct point, point includes a struct timestamp(such as HelloWorld.idl),in this way, fastddsspy will come to  Segmentation fault. However, if IDL include a structure HelloWorld, HelloWorld includes a struct point, point don't include  any struc (like HelloWorld_OK.idl), fastddsspy will run ok.

HelloWorld_OK.idl
      struct point{
	      short x;};
      struct HelloWorld{
	      point  pos;
	      unsigned long index;};

HelloWorld.idl
      struct timestamp{
	      short h;};
      struct point{
	      timestamp ts;
	      short x;};
      struct HelloWorld{
	      point  pos;
	      unsigned long index;};

step1:
   fastddsgen -typeobjcet HelloWorld.idl

step2:
    DomainParticipantQos pqos;
    pqos.wire_protocol().builtin.typelookup_config.use_server = true;

   eprosima::fastdds::dds::DomainParticipant* participant_;
   participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);

    eprosima::fastdds::dds::TypeSupport type_;
    type_(new HelloWorldPubSubType())
    type_.register_type(participant_);
    type_->auto_fill_type_object(false);
    type_->auto_fill_type_information(true);

step3:
    HelloWorld hello_; 
    hello_.index(0);
    hello_.pos().ts().h(10);
    hello_.pos().x(10);
    writer_->write(&hello_);

**Comment by wannastar** [comment]
it's same with this .
publisher:  TypeLookupService -x complete 
fastddsspy will come to Segmentation fault again.

**Comment by juanlofer-eprosima** [comment]
Hi @wannastar 

What you are describing is one of the detected issues with Dynamic Types currently present in master branch.
An exhaustive [refactor](https://github.com/eProsima/Fast-DDS/pull/3392) tackling all these issues and aiming to fully comply with the OMG standard is currently being performed, and it is expected to be completed in the upcoming months.

For the time being, there exists an **unsupported** [branch](https://github.com/eProsima/Fast-DDS/tree/bugfix/complex-dynamic-types) containing a bunch of temporary workarounds which probably would solve your issue.

**Comment by wannastar** [comment]
okay, i got it. i'm looking forward to a better fastdds tool.
